export const subscriptionFeatures = [
	{
		name: "Base Plan",
		features: [
			"Provides One-on-One Consultations, Review and Revision with one of our seasoned Designers",
			"This service utilizes ZOOM calls, Site Surveys, detailed Client Meetings and a thorough Revision Process",
			"Your personal Designer will also bring a comprehensive understanding and set of recommendations for the Installation and Maintenance aspects of your project",
			"Enjoy One-on-One Consultations, Review and Revision with one of our seasoned Landscape Designers",
			"Through ZOOM calls, Site Surveys, detailed Client Meetings and a thorough Revision Process, our personalized Design Services are sure to provide you the new landscape that perfectly realizes your Wants and Needs, as well as meeting your site’s Opportunities and Constraints",
			"Our firm offers a combined 120+years of Professional, Certified Landscape Design experience",
			"Our Designers are not only experts in the field; they will also bring a comprehensive understanding and set of recommendations for the Installation and Maintenance aspects of your project",
			"Contact us at mailto:info@customscape.ai today to begin planning the landscape of your dreams!",
		],
	},
	{
		name: "Personalized Plan",
		features: [
			"Perfect for the Homeowner or Property Owner",
			"Select from 10 different Landscape Themes",
			"Receive a Scaled Overhead Planting Plan, up to 5 Digital Before/After Landscape Images and a detailed Plant & Material List",
			"Provides all the finalized documents you would typically receive from a Landscape Architect at a fraction of the cost in a fraction of the time",
			"The Completed Design Package gives you everything needed to either put the project “out-to-bid” with local Installation Contractors or begin staging the project for DIY",
			"Perfect for the Homeowner or Property Owner that wants to re-design an existing landscape or create a new landscape using our AI-assisted software",
			"This one-time use purchase allows you to select from 10 different Landscape Themes, answer some basic questions about what Landscape Elements you want in the new Design and upload photos of the existing site",
			"The Base User Level offers example preliminary Designs from up to 3 different Landscape Themes before you select the one with the Layout and Material most preferred",
			"The Landscape Design AI then generates a Scaled Overhead Planting Plan, up to 5 Digital Before/After Landscape Images and a detailed Plant & Material List (including Unit Quantities, Required Environmental Conditions and On-Center Spacing) – all based on the site’s Agriculture Growing Zone and specific input from you",
			"The Base User Level provides the finalized documents you would typically receive from a Landscape Architect at a fraction of the cost in a fraction of the time",
			"The Completed Design Package gives you everything needed to either put the project “out-to-bid” with local Installation Contractors or begin staging the project for DIY. ",
		],
	},
	{
		name: "Pro Plan",
		features: [
			"Includes everything from the Base User Level and further allows you to customize all the items in the Design",
			"Ability to change the layout of specific plants, substitute AI-selected Plants with other site-appropriate species and change any Landscape Material",
			"Choose your preferred Plants from a catalogue of over 1000 species and a Material catalogue of over 100 items ",
			"Opportunity to upload a specific Plant/Material List for use in the Final Design",
			"The Completed Design Package can include up to 10 Digital Before/After Landscape images",
			"Includes everything from the Base User Level and further allows you to customize all the items in the Design.",
			"Select from your uploaded photos and view a specific site area under each of the 10 available Landscape Themes before deciding on your favorite",
			"Ability to change the layout of specific plants, substitute AI-selected Plants with other site-appropriate species and change any Landscape Material that may be in the design (pathway material, fencing material, stepping stone type, edging material, etc.)",
			"Choose your preferred Plants from a catalogue of over 1000 species and a Material catalogue of over 100 items, or upload a specific Plant/Material List for use in the Final Design",
			"The Completed Design Package can include up to 10 Digital Before/After Landscape images, allowing you to envision each area of your new yard or garden",
			"Pro Users truly have the ability to fully customize every item in their new Landscape Design",
		],
	},
	{
		name: "Commercial Plan",
		features: [
			"Subscription Service intended for an existing Landscape Maintenance/Installation Company, Pool Construction Company, Builder or Property Manager",
			"Ability to watermark all generated documents with your company’s specific Branding (Logo, Contact Info, etc.)",
			"Commercial Users enjoy all the AI services offered from the Base User Level and the Pro User Upgrade for multiple Properties",
			"This subscription is a powerful Sales Tool you can easily incorporate into daily operations to increase Landscape Enhancement opportunities ",
			"The Commercial Use Subscription is an Annual subscription",
			"This Subscription Service is intended for an existing Landscape Maintenance/Installation Company, Pool Construction Company, Builder or Property Manager who wants to streamline and/or improve the Landscape Design process of their business",
			"The Commercial Use Subscription gives you the ability to watermark all generated documents with your company’s specific Branding (Logo, Contact Info, etc.)",
			"Commercial Users enjoy all the AI services offered from the Base User Level and the Pro User Upgrade for multiple Properties.",
			"The Commercial Use Subscription is a powerful Sales Tool you can easily incorporate into daily operations to increase Landscape Enhancement opportunities you may not currently be realizing within your existing client portfolio",
			"The Commercial Use Subscription is an Annual subscription billed monthly and can pay for itself with your first sale",
		],
	},
];
